"use strict";
(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;else{root.BurrowObservatory=api;api.start(root)}})(typeof globalThis==="object"?globalThis:this,function(){
const activeStates=new Set(["active","working","knocking","thinking"]),documents=new WeakMap();
const escapeHtml=value=>String(value==null?"":value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
const text=(value,fallback="—")=>escapeHtml(value||fallback);
function eventFeed(villagers){return villagers.flatMap(v=>(v.history||[]).map((event,index)=>({...event,agent_id:event.agent_id||v.id,agent_name:v.name,_stable:`${v.id}:${index}`}))).sort((a,b)=>Date.parse(b.ts)-Date.parse(a.ts)||a._stable.localeCompare(b._stable))}
function viewModel(snapshot){const residents=new Map(snapshot.residents.map(item=>[item.match&&item.match.agent_id,item]));const people=snapshot.villagers.map((v,index)=>{const resident=residents.get(v.id),angle=index/Math.max(snapshot.villagers.length,1)*Math.PI*2-Math.PI/2,radius=31+index%3*7;return{...v,role:resident&&resident.meta&&resident.meta.role,capabilities:resident&&resident.capabilities,body:resident&&resident.body,x:50+Math.cos(angle)*radius,y:50+Math.sin(angle)*radius}});return{people,tasks:snapshot.tasks,approvals:snapshot.approvals,events:eventFeed(people),active:people.filter(p=>activeStates.has(p.state)).length}}
function payloadSummary(event){const payload=event.payload||{};return payload.message||payload.tool||payload.command||payload.task||payload.status||Object.entries(payload).slice(0,3).map(([key,value])=>`${key}: ${typeof value==="object"?JSON.stringify(value):value}`).join(" · ")}
function eventRows(events){return events.length?events.map(event=>`<div class="event-row" data-agent="${escapeHtml(event.agent_id)}"><time class="event-time">${text(new Date(event.ts).toLocaleString())}</time><b class="event-agent">${text(event.agent_name,event.agent_id)}</b><span class="event-type">${text(event.type)}</span><span class="event-source">${text(event.source)}</span><span class="event-payload" title="${text(payloadSummary(event))}">${text(payloadSummary(event),"No payload summary")}</span></div>`).join(""):'<p class="empty">No retained activity in this snapshot.</p>'}
function agentDetail(person,approvals){const pending=approvals.filter(item=>item.agent_id===person.id&&item.state==="pending"),capabilities=person.capabilities&&person.capabilities.tools;return`<p class="detail-kicker">AGENT DOSSIER / READ ONLY</p><h2 id="drawer-name" class="detail-name">${text(person.name,person.id)}</h2><span class="detail-state">${text(person.state)}</span><div class="detail-grid"><div><span>IDENTITY</span><b>${text(person.id)}</b></div><div><span>ROLE</span><b>${text(person.role,person.residency)}</b></div><div><span>PROJECT</span><b>${text(person.project)}</b></div><div><span>LOCATION</span><b>${text(person.place,person.base)}</b></div><div><span>WORKING DIR</span><b>${text(person.cwd)}</b></div><div><span>MOOD</span><b>${text(person.mood&&person.mood.name)}</b></div><div><span>LAST SIGNAL</span><b>${text(person.last_ts)}</b></div><div><span>TOOLS</span><b>${text(Array.isArray(capabilities)?capabilities.join(", "):"")}</b></div></div>${person.body?`<p class="detail-line">${text(person.body)}</p>`:""}<section class="detail-section"><h3>Human attention</h3>${pending.length?pending.map(item=>`<p class="detail-approval">${text(item.message,item.action)}</p>`).join(""):'<p class="empty">No pending decisions.</p>'}</section><section class="detail-section"><h3>Recent activity</h3>${(person.history||[]).slice().reverse().map(event=>`<div class="detail-event"><b>${text(event.type)}</b><span>${text(new Date(event.ts).toLocaleString())} · ${text(payloadSummary(event),event.source)}</span></div>`).join("")||'<p class="empty">No retained history.</p>'}</section>`}
function openAgent(document,id){const state=documents.get(document),person=state&&state.model.people.find(item=>item.id===id);if(!person)return false;document.getElementById("agent-detail").innerHTML=agentDetail(person,state.model.approvals);const drawer=document.getElementById("agent-drawer");drawer.classList.add("open");drawer.setAttribute("aria-hidden","false");document.getElementById("drawer-scrim").classList.add("open");drawer.focus();return true}
function closeAgent(document){const drawer=document.getElementById("agent-drawer");drawer.classList.remove("open");drawer.setAttribute("aria-hidden","true");document.getElementById("drawer-scrim").classList.remove("open")}
function render(snapshot,document){const model=viewModel(snapshot),previous=documents.get(document)||{filter:"all"};documents.set(document,{...previous,model});const set=(id,value)=>{document.getElementById(id).textContent=value};set("resident-count",model.people.length);set("active-count",model.active);set("task-count",model.tasks.filter(task=>!["done","cancelled","failed"].includes(task.state)).length);set("approval-count",model.approvals.filter(item=>item.state==="pending").length);set("schema-version",`v${snapshot.schema_version}`);set("generation",snapshot.generation);set("cursor",snapshot.cursor);
document.getElementById("fleet-pulse").innerHTML='<span class="pulse-core"></span>'+model.people.map(p=>`<button class="signal-button" type="button" data-open-agent="${escapeHtml(p.id)}" aria-label="Inspect ${text(p.name)}" style="--x:${p.x}%;--y:${p.y}%;--signal:${escapeHtml(p.accent||"#d8ff3e")}"><i class="signal-dot"></i><span class="signal-label">${text(p.name)}</span></button>`).join("");
document.getElementById("residents").innerHTML=model.people.length?model.people.map((p,index)=>`<button class="resident-button" type="button" data-open-agent="${escapeHtml(p.id)}"><span class="resident" style="animation-delay:${index*35}ms"><span class="resident-initial" style="--accent:${escapeHtml(p.accent||"#d8ff3e")}">${text((p.name||"?")[0])}</span><span><b class="name">${text(p.name)}</b><small class="meta">${text(p.role,p.project||"visitor")}</small></span><span class="state">${text(p.state)}</span></span></button>`).join(""):'<p class="empty">No residents in this snapshot.</p>';
document.getElementById("tasks").innerHTML=model.tasks.length?model.tasks.map((task,index)=>`<div class="task" style="animation-delay:${index*35}ms"><span><b class="item-title">${text(task.title)}</b><small class="item-meta">${text(task.claimant,"unclaimed")} · ${text((task.required_skills||[]).join(", "),"no skill constraint")}</small></span><span class="state">${text(task.state)}</span></div>`).join(""):'<p class="empty">The workstream is clear.</p>';
document.getElementById("approvals").innerHTML=model.approvals.length?model.approvals.map((approval,index)=>`<div class="approval" style="animation-delay:${index*35}ms"><span><b class="item-title">${text(approval.message,approval.action)}</b><small class="item-meta">${text(approval.agent_id)} · ${text(approval.project)}</small></span><span class="state">${text(approval.state)}</span></div>`).join(""):'<p class="empty">No human decisions queued.</p>';
const filter=document.getElementById("event-filter"),selected=filter.value||previous.filter;filter.innerHTML='<option value="all">ALL AGENTS</option>'+model.people.map(p=>`<option value="${escapeHtml(p.id)}">${text(p.name)}</option>`).join("");filter.value=model.people.some(p=>p.id===selected)?selected:"all";document.getElementById("event-feed").innerHTML=eventRows(model.events.filter(event=>filter.value==="all"||event.agent_id===filter.value));const evaluated=Date.parse(snapshot.evaluated_at);set("snapshot-age",Number.isFinite(evaluated)?new Date(evaluated).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit",second:"2-digit"}):"UNKNOWN TIME")}
function bindInteractions(document){document.addEventListener("click",event=>{const trigger=event.target.closest&&event.target.closest("[data-open-agent]");if(trigger)openAgent(document,trigger.dataset.openAgent)});document.getElementById("drawer-close").addEventListener("click",()=>closeAgent(document));document.getElementById("drawer-scrim").addEventListener("click",()=>closeAgent(document));document.addEventListener("keydown",event=>{if(event.key==="Escape")closeAgent(document)});document.getElementById("event-filter").addEventListener("change",event=>{const state=documents.get(document);state.filter=event.target.value;document.getElementById("event-feed").innerHTML=eventRows(state.model.events.filter(item=>state.filter==="all"||item.agent_id===state.filter))})}
function start(root){bindInteractions(root.document);const baseUrl=new URLSearchParams(root.location.search).get("backend")||"",connection=root.document.querySelector(".connection"),label=root.document.getElementById("connection-label");const transport=root.BurrowStateTransport.createStateTransport({fetch:root.fetch.bind(root),EventSource:root.EventSource,baseUrl,onStatus(status){connection.className=`connection ${status}`;label.textContent=status.toUpperCase()},onState(snapshot){render(snapshot,root.document)},warn(message){root.console.warn("Burrow Observatory:",message)}});transport.poll().then(()=>transport.connect());return transport}
return{escapeHtml,eventFeed,viewModel,payloadSummary,agentDetail,render,openAgent,closeAgent,start}});
